### PR TITLE
Add parameters and expand example section of README.md

### LINKED ISSUE #12: Add SITL options that can be passed to the dronekit runner to Readme/help
If you run ``dronekit-sitl`` or ``dronekit-sitl --help`` you get the following options:
```
ubuntu@ubuntu:~$ dronekit-sitl 
Please specify one of:
  dronekit-sitl --list
  dronekit-sitl --reset
  dronekit-sitl <copter(-version)>
  dronekit-sitl <plane(-version)>
```

However I can see from your example I can actually specify more options (model, home, IO, s):
```
dronekit-sitl copter-3.4-dev -I0 -S --model quad --home=-35.363261,149.165230,584,353
```
Is there a list of all options we can pass anywhere?

The help above and the readme.md should make it clear that there are additional commands that can be supported.

### PR DESCRIPTION
**Pull request by hamishwillee**
This partially fixes #12 (it would still be good if the parameters could be fetched and displayed using `` dronekit-sitl --help``.

This fixes the example, which was previously ambiguous (not clear what the mavproxy command was doing, or that it needed to be run in a separate terminal)

### CODE REVIEW

**Comment by tcr3dr** [comment]
This looks good to me.

What remains to be seen if `dronekit-sitl copter-3.3-rc5 --help` is good enough, since `dronekit-sitl --help` is ambiguous.

**Comment by hamishwillee** [comment]
> What remains to be seen if dronekit-sitl copter-3.3-rc5 --help is good enough, since dronekit-sitl --help is ambiguous.

Perhaps ``dronekit-sitl --help`` should include instructions to be able to run ``dronekit-sitl copter-3.3-rc5 --help``

**Comment by tcr3dr** [comment]
@hamishwillee Oh, obviously. I'll open that issue!

**Comment by tcr3dr** [comment]
https://github.com/3drobotics/dronekit-sitl-runner/issues/23

**Pull request merged**
